name: 'Islandora Repository Item Metadata'
description: 'Starter content type and fields to hold descriptive metadata.'
type: 'islandora'
recipes:
  - islandora_metadata_vocabularies
  - islandora_repository_item
install:
  - controlled_access_terms
  - field_group
  - geolocation
config:
  actions:
    core.entity_form_display.node.islandora_object.default:
      setComponents:
        -
          name: field_abstract
          options:
            type: text_textarea
            weight: 8
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_alt_title
          options:
            type: string_textfield
            weight: 2
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        - 
          name: field_alt_title
          options:
            type: string_textfield
            weight: 2
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
           name: field_classification
           options:
            type: string_textfield
            weight: 27
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        - 
          name: field_coordinates
          options:
            type: geolocation_latlng
            weight: 23
            region: content
            settings: {  }
            third_party_settings: {  }
        -
          name: field_coordinates_text
          options:
            type: string_textfield
            weight: 25
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_copyright_date
          options:
            type: edtf_default
            weight: 13
            region: content
            settings:
              strict_dates: false
              intervals: true
              sets: false
            third_party_settings: {  }
        -
          name: field_date_captured
          options:
            type: edtf_default
            weight: 15
            region: content
            settings:
              strict_dates: false
              intervals: true
              sets: false
            third_party_settings: {  }
        -
          name: field_date_modified
          options:
            type: edtf_default
            weight: 17
            region: content
            settings:
              strict_dates: false
              intervals: true
              sets: false
            third_party_settings: {  }
        -
          name: field_date_valid
          options:
            type: edtf_default
            weight: 14
            region: content
            settings:
              strict_dates: false
              intervals: true
              sets: false
            third_party_settings: {  }
        -
          name: field_description
          options:
            type: string_textarea
            weight: 7
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_dewey_classification
          options:
            type: string_textfield
            weight: 24
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_edition
          options:
            type: string_textfield
            weight: 15
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_edtf_date
          options:
            type: edtf_default
            weight: 14
            region: content
            settings:
              strict_dates: false
              intervals: false
              sets: false
            third_party_settings: {  }
        -
          name: field_edtf_date_created
          options:
            type: edtf_default
            weight: 12
            region: content
            settings:
              strict_dates: false
              intervals: false
              sets: false
            third_party_settings: {  }
        -
          name: field_edtf_date_issued
          options:
            type: edtf_default
            weight: 11
            region: content
            settings:
              strict_dates: false
              intervals: false
              sets: false
            third_party_settings: {  }
        -
          name: field_extent
          options:
            type: string_textfield
            weight: 12
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_frequency
          options:
            type: entity_reference_autocomplete
            weight: 16
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_full_title
          options:
            type: string_textarea
            weight: 1
            region: content
            settings:
              rows: 2
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_genre
          options:
            type: entity_reference_autocomplete
            weight: 13
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_geographic_subject
          options:
            type: entity_reference_autocomplete
            weight: 14
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_identifier
          options:
            type: string_textfield
            weight: 16
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_isbn
          options:
            type: string_textfield
            weight: 17
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_language
          options:
            type: entity_reference_autocomplete
            weight: 12
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_lcc_classification
          options:
            type: string_textfield
            weight: 25
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_linked_agent
          options:
            type: typed_relation_default
            weight: 3
            region: content
            settings:
              match_operator: CONTAINS
              size: 60
              placeholder: ''
              match_limit: 10
            third_party_settings: {  }
        -
          name: field_local_identifier
          options:
            type: string_textfield
            weight: 19
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_member_of
          options:
            type: entity_reference_autocomplete
            weight: 14
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_mode_of_issuance
          options:
            type: entity_reference_autocomplete
            weight: 15
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_model
          options:
            type: options_select
            weight: 0
            region: content
            settings: {  }
            third_party_settings: {  }
        -
          name: field_note
          options:
            type: text_textarea
            weight: 9
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_oclc_number
          options:
            type: string_textfield
            weight: 18
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_physical_form
          options:
            type: entity_reference_autocomplete
            weight: 11
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_pid
          options:
            type: string_textfield
            weight: 20
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_place_published
          options:
            type: string_textfield
            weight: 9
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_place_published_country
          options:
            type: entity_reference_autocomplete
            weight: 10
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_publisher
          options:
            type: string_textfield
            weight: 8
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_resource_type
          options:
            type: options_select
            weight: 9
            region: content
            settings: {  }
            third_party_settings: {  }
        -
          name: field_rights
          options:
            type: text_textarea
            weight: 16
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_subject
          options:
            type: entity_reference_autocomplete
            weight: 11
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_subject_general
          options:
            type: entity_reference_autocomplete
            weight: 9
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_subjects_name
          options:
            type: entity_reference_autocomplete
            weight: 12
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_table_of_contents
          options:
            type: text_textarea
            weight: 10
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_temporal_subject
          options:
            type: entity_reference_autocomplete
            weight: 13
            region: content
            settings:
              match_operator: CONTAINS
              match_limit: 10
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_viewer_override
          options:
            type: options_select
            weight: 17
            region: content
            settings: {  }
            third_party_settings: {  }
        -
          name: field_weight
          options:
            type: number
            weight: 16
            region: content
            settings:
              placeholder: ''
            third_party_settings: {  } 
        -
          name: title
          options:
            type: string_textfield
            weight: 0
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
      setThirdPartySettings:
        - 
          module: field_group
          key: group_title_and_contributors
          value:
            children:
              - title
              - field_full_title
              - field_alt_title
              - field_linked_agent
            label: 'Title and Contributors'
            region: content
            parent_name: ''
            weight: 1
            format_type: details
            format_settings:
              classes: ''
              show_empty_fields: true
              id: ''
              open: true
              description: ''
              required_fields: true
