name: 'Islandora Repository Item Metadata'
description: 'Starter content type and fields to hold descriptive metadata.'
type: 'islandora'
recipes:
  - islandora_metadata_vocabularies
  - islandora_repository_item
install:
  - controlled_access_terms
  - field_group
  - geolocation
config:
  actions:
    core.entity_form_display.node.islandora_object.default:
      setComponents:
        -
          name: field_abstract
          options:
            type: text_textarea
            weight: 8
            region: content
            settings:
              rows: 5
              placeholder: ''
            third_party_settings: {  }
        -
          name: field_alt_title
          options:
            type: string_textfield
            weight: 2
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }



